
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kekphqlascqtujohaejq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtla3BocWxhc2NxdHVqb2hhZWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTIwMTAsImV4cCI6MjA2NTUyODAxMH0.dzPzFE4Wu3gig9m8guqDFJyxj07QuXVHXKQtc0hwbb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
