// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbmjbmmcksfirjoyuyfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRibWpibW1ja3NmaXJqb3l1eWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mzc5MTEsImV4cCI6MjA2NDExMzkxMX0.HeRoTr7jJG93QEgwbdJ0c3l_EQ6Tpy8kFOaET6-HSqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);